### ISSUE TITLE
Absolute paths in the generated PBRT file

### ISSUE THREAD

**Issue by hblasins** [RenderToolbox3/mPbrt#4]
For the test scene I am using RTB4+mPBRT introduce absolute paths for all the texture files. This causes problems when the computation is Dockerized because the absolute paths are not accessible from inside the Docker container (i.e. volumes are not being mounted).

For example
```
Texture "black_metal_spectrum" "spectrum" "imagemap"
"string filename" "/share/wandell/data/3DScenes/City/black_metal.exr"
```

**Comment by benjamin-heasly** [comment]
Hi.  I can see how this would be an issue, but I would need more details before I can help.  Can you share the test scene so that I can reproduce the error on my end?

**Comment by hblasins** [comment]
I'll do this later today.

Sent from a mobile device.

Dnia 15.02.2017 o godz. 06:52 Ben Heasly <notifications@github.com<mailto:notifications@github.com>> napisał(a):


Hi. I can see how this would be an issue, but I would need more details before I can help. Can you share the test scene so that I can reproduce the error on my end?

**Comment by benjamin-heasly** [comment]
I think we resolved this in another thread.
